# ========================
# H2 Database (JPA)
# ========================
spring.datasource.url=jdbc:h2:file:./data/estore_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================
# MongoDB
# ========================
spring.data.mongodb.uri=mongodb+srv://estore:estore123@estore-cluster.dnulogk.mongodb.net/estore_mongo?retryWrites=true&w=majority&appName=estore-cluster

# ========================
# Server
# ========================
server.port=8080

# ========================
# JWT
# ========================
jwt.secret=estore_super_secret_key_must_be_at_least_256_bits_long_for_hs256
jwt.expiration=86400000

# ========================
# Data seeding
# ========================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always